export const GAME_OPTIONS = [
  "Mario Kart World",
  "Mario Kart 8 Deluxe",
  "Mario Party Superstars",
  "Super Mario Party",
  "Super Smash Bros. Ultimate",
  "Jackbox Party Pack",
  "Super Mario 3D World + Bowser's Fury",
  "New Super Mario Bros. U Deluxe",
  "Kirby et le Monde Oublié",
  "Kirby's Return to Dream Land Deluxe",
  "Overcooked! 2",
  "It Takes Two",
  "Unravel Two",
  "Cuphead",
  "Luigi's Mansion 3",
  "Pikmin 4",
  "Animal Crossing: New Horizons",
  "Minecraft",
  "Terraria",
  "Stardew Valley",
  "Don't Starve Together",
  "Splatoon 3",
  "Tetris 99",
  "Mario Strikers: Battle League",
  "Mario Golf: Super Rush",
  "Mario Tennis Aces",
  "Rocket League",
];
